# Generated by Django 5.1.2 on 2026-02-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_feedbackresponse_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('yes_no', 'Yes / No'), ('rating', 'Rating (1–5)')], max_length=20),
        ),
    ]
