# Generated by Django 5.1.2 on 2026-01-28 14:00

import instructor.models.accounts
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', instructor.models.accounts.CustomUserManager()),
            ],
        ),
    ]
